language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install -r tests/requirements.txt
  - pip install coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
  - nosetests --with-coverage --cover-erase --cover-package=instructions
after_success:
  - coveralls
